apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-1-staging
  namespace: argocd
  labels:
    env: staging
    type: app
spec:
  project: default
  source:
    path: app-1/staging
    repoURL: 'https://github.com/MarcArumi/argocd-test.git'
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: staging
  syncPolicy:
    #automated:
    #  selfHeal: true
    #  prune: true
    syncOptions:
    - CreateNamespace=true